# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d1958b420ba0b48aae06e8ae040b5206f41222d7d757e78d0058786a9b7e294dc37b8624f19d9c3ec0819c42ce65fc8649e5a71206e22da5e7c9452db26ba45b

test:
  secret_key_base: dbd8f4b4a1415336df934e3b0e2d82de84d8f0e0fad52277fbfba7b0008dc40a561dc512f90152be4aba1e963d620373938a9c9d544d8c17711bd438c76f31b2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
